name: lumo_book
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter_riverpod: ^2.3.6

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  intl: ^0.18.1
  share_plus: ^11.0.0
  url_launcher: ^6.3.2

  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  open_filex: ^4.3.2

  http: '>=0.13.6 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/bookmark_black.png
    - assets/icon/bookmark_light.png
    - assets/icon/discount_black.png
    - assets/icon/discount_light.png
    - assets/icon/home_black.png
    - assets/icon/home_light.png
    - assets/icon/search_black.png
    - assets/icon/search_light.png
    - assets/icon/user_black.png
    - assets/icon/user_light.png
    - assets/icon/tag.png
    - assets/icon/google_icon.png
    - assets/icon/facebook_icon.png
    - assets/icon/cart_light.png
    - assets/image/banner_one.png
    - assets/image/banner_two.png
    - assets/image/payment.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-Regular.ttf
          weight: 400