name: lumo_book
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase (compatible versions)
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.10

  # State Management
  flutter_riverpod: ^2.3.6

  # Auth
  google_sign_in: ^6.2.1

  # UI & Utilities
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  intl: ^0.20.2
  share_plus: ^11.0.0
  url_launcher: ^6.3.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10

  # Files & Network
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  open_filex: ^4.3.2
  http: ^1.2.2


  # Viewing
  webview_flutter: ^4.4.1
  syncfusion_flutter_pdfviewer: ^30.1.40

  # Device Info
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/bookmark_black.png
    - assets/icon/bookmark_light.png
    - assets/icon/discount_black.png
    - assets/icon/discount_light.png
    - assets/icon/home_black.png
    - assets/icon/home_light.png
    - assets/icon/search_black.png
    - assets/icon/search_light.png
    - assets/icon/user_black.png
    - assets/icon/user_light.png
    - assets/icon/tag.png
    - assets/icon/google_icon.png
    - assets/icon/facebook_icon.png
    - assets/icon/cart_light.png
    - assets/image/banner_one.png
    - assets/image/banner_two.png
    - assets/image/payment.jpg
    - assets/image/logo_1.png
    - assets/image/logo_2.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-Regular.ttf
          weight: 400
