// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsrVpQElNFUAjBdSEeuUGBOkvPpZvd_Vs',
    appId: '1:817372456116:web:73a408b42a7d544fc7e3e1',
    messagingSenderId: '817372456116',
    projectId: 'lumoapp-33e70',
    authDomain: 'lumoapp-33e70.firebaseapp.com',
    storageBucket: 'lumoapp-33e70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9uTU4d6gQrCik4f8hpLcIZ0QFJc7r2E',
    appId: '1:817372456116:android:060a44c3997dffffc7e3e1',
    messagingSenderId: '817372456116',
    projectId: 'lumoapp-33e70',
    storageBucket: 'lumoapp-33e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xPD7HPFDOuH4L96arCUFZBSDg75SfAY',
    appId: '1:817372456116:ios:1ca8350b5dad5b3cc7e3e1',
    messagingSenderId: '817372456116',
    projectId: 'lumoapp-33e70',
    storageBucket: 'lumoapp-33e70.firebasestorage.app',
    androidClientId: '817372456116-nl00g6a1trk2nt4hp3ih6dnt6vfg66ka.apps.googleusercontent.com',
    iosClientId: '817372456116-nr5q0n33o9jccpnfg3ifb2sa4969ffqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumoBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6xPD7HPFDOuH4L96arCUFZBSDg75SfAY',
    appId: '1:817372456116:ios:1ca8350b5dad5b3cc7e3e1',
    messagingSenderId: '817372456116',
    projectId: 'lumoapp-33e70',
    storageBucket: 'lumoapp-33e70.firebasestorage.app',
    androidClientId: '817372456116-nl00g6a1trk2nt4hp3ih6dnt6vfg66ka.apps.googleusercontent.com',
    iosClientId: '817372456116-nr5q0n33o9jccpnfg3ifb2sa4969ffqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumoBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsrVpQElNFUAjBdSEeuUGBOkvPpZvd_Vs',
    appId: '1:817372456116:web:969f4c143cc79b8bc7e3e1',
    messagingSenderId: '817372456116',
    projectId: 'lumoapp-33e70',
    authDomain: 'lumoapp-33e70.firebaseapp.com',
    storageBucket: 'lumoapp-33e70.firebasestorage.app',
  );

}